### ISSUE TITLE
PA Review: Station CRD

### ISSUE THREAD

**Issue by Edwardc148** [Edwardc148/Jukebox#4]
- [x] Backend DB: Able to create a new station with songs
- [x] Backend DB: Able to read a station and redirect to show page from anywhere on site
- [x] Backend DB: Able to delete an existing station
- [x] Styling (looks presentable)
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

By choice there is no update

**Comment by AAlfarho** [comment]
Amazing job on the station CRD. The station show page is amazing, having the background image same as the artwork looks great, the same goes for the progress of the song!

## Functionality
- [ ] (Optional) Handle non-existing stations, for example `https://jukebox-aa.herokuapp.com/#/stations/18` should display something like no station found.
- [x] There seems to be an issue with the Stations Index, they don't always have the same image, is this expected? I manage to have different images displaying just by refreshing or clicking on a station and then back to `my stations`.

## Styling 
- [x] On 13-inch screens, your media player is not shown. Take a look out for that.
- [x] The stations overlap with the media player.
   
![screen shot 2018-02-08 at 10 50 54 am](https://user-images.githubusercontent.com/1103663/35992044-f9cb2af2-0cbd-11e8-9a9f-5bcd836e42fe.png)

- [x] Reduce the brightness of the color (red) when hovering over the delete. Like
![screen shot 2018-02-08 at 10 36 52 am](https://user-images.githubusercontent.com/1103663/35991428-05f026e0-0cbc-11e8-9f12-db72a6ace61c.png)
- [x] The background image is a great idea, however, there a couple of details to take into account.
  - [x] The image will expand to fit the screen, so it has to be a high-quality image so it doesn't distort.
  - [x] Set some transparency on the media player, so that that controls and your github link is still visible under bright or dark images.

**Comment by AAlfarho** [comment]
Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by AAlfarho** [comment]
Great work on the new updated.

Add `background-attachment: fixed;` so that the gradient stretches as the page does.
